export const products = {
	apple: [
		{
			id: "0",
			brand: "apple",
			title: "iPhone 14Pro",
			price: 999,
			img: "/img/apple/iPhone_14Pro.jpg",
			ram: "6GB",
			color: "spaceBlack",
			year: 2022,
			reviews: []
		},
		{
			id: "1",
			brand: "apple",
			title: "iPhone 14",
			price: 799,
			img: "/img/apple/iPhone_14.jpg",
			ram: "6GB",
			color: "purple",
			year: 2022,
			reviews: []
		},
		{
			id: "2",
			brand: "apple",
			title: "iPhone 13Pro",
			price: 699,
			img: "/img/apple/iPhone_13Pro.jpg",
			ram: "6GB",
			color: "alpineGreen",
			year: 2021,
			reviews: []
		},
		{
			id: "3",
			brand: "apple",
			title: "iPhone 13",
			price: 599,
			img: "/img/apple/iPhone_13.jpg",
			ram: "4GB",
			color: "pink",
			year: 2021,
			reviews: []
		},
		{
			id: "4",
			brand: "apple",
			title: "iPhone 12Pro",
			price: 539,
			img: "/img/apple/iPhone_12Pro.jpg",
			ram: "6GB",
			color: "gold",
			year: 2020,
			reviews: []
		},
		{
			id: "5",
			brand: "apple",
			title: "iPhone 12",
			price: 499,
			img: "/img/apple/iPhone_12.jpg",
			ram: "4GB",
			color: "green",
			year: 2020,
			reviews: []
		},
		{
			id: "6",
			brand: "apple",
			title: "iPhone 11Pro",
			price: 459,
			img: "/img/apple/iPhone_11Pro.jpg",
			ram: "4GB",
			color: "gray",
			year: 2019,
			reviews: []
		},
		{
			id: "7",
			brand: "apple",
			title: "iPhone 11",
			price: 419,
			img: "/img/apple/iPhone_11.jpg",
			ram: "4GB",
			color: "red",
			year: 2019,
			reviews: []
		},
		{
			id: "8",
			brand: "apple",
			title: "iPhone XS",
			price: 399,
			img: "/img/apple/iPhone_XS.jpg",
			ram: "4GB",
			color: "spaceGray",
			year: 2018,
			reviews: []
		},
		{
			id: "9",
			brand: "apple",
			title: "iPhone XR",
			price: 319,
			img: "/img/apple/iPhone_XR.jpg",
			ram: "3GB",
			color: "yellow",
			year: 2018,
			reviews: []
		},
	],
	motorola: [
		{
			id: "10",
			brand: "motorola",
			title: "Defy 4",
			price: 40,
			img: "/img/motorola/motorola (2).jpg",
			ram: "1 GB",
			color: "beige",
			year: 2003,
			reviews: []
		},
		{
			id: "11",
			brand: "motorola",
			title: "Moto C",
			price: 38,
			img: "/img/motorola/motorola (3).jpg",
			ram: "2 GB",
			color: "grey",
			year: 2005,
			reviews: []
		},
		{
			id: "12",
			brand: "motorola",
			title: "Moto G9 plus",
			price: 95,
			img: "/img/motorola/motorola (4).jpg",
			ram: "64 GB",
			color: "black",
			year: 2009,
			reviews: []
		},
		{
			id: "13",
			brand: "motorola",
			title: "Moto E7 plus",
			price: 110,
			img: "/img/motorola/motorola (5).jpg",
			ram: "64 GB",
			color: "aqua",
			year: 2018,
			reviews: []
		},
		{
			id: "14",
			brand: "motorola",
			title: "Moto G Pure ",
			price: 85,
			img: "/img/motorola/motorola (6).jpg",
			ram: "12 GB",
			color: "beige",
			year: 2021,
			reviews: []
		},
		{
			id: "15",
			brand: "motorola",
			title: "Edge 40",
			price: 250,
			img: "/img/motorola/motorola (7).jpg",
			ram: "12 GB",
			color: "green",
			year: 2005,
			reviews: []
		},
		{
			id: "16",
			brand: "motorola",
			title: "Moto G Power",
			price: 150,
			img: "/img/motorola/motorola (8).jpg",
			ram: "32 GB",
			color: "green",
			year: 2010,
			reviews: []
		},
		{
			id: "17",
			brand: "motorola",
			title: "Moto G4",
			price: 76,
			img: "/img/motorola/motorola (9).jpg",
			ram: "126 GB",
			color: "black",
			year: 2023,
			reviews: []
		},
		{
			id: "18",
			brand: "motorola",
			title: "Moto G 72",
			price: 96,
			img: "/img/motorola/motorola.jpg",
			ram: "32 GB",
			color: "black",
			year: 2015,
			reviews: []
		},
		{
			id: "19",
			brand: "motorola",
			title: "Razr",
			price: 500,
			img: "/img/motorola/motorola (3).jpg",
			ram: "64 GB",
			color: "aqua",
			year: 2018,
			reviews: []
		},
	],
	nokia: [
		{
			id: "20",
			brand: "nokia",
			title: "Nokia 9 PureView",
			price: 699,
			img: "/img/nokia/Nokia_9_PureView.jpg",
			ram: "6GB",
			color: "Midnight Blue",
			year: 2023,
			reviews: []
		},
		{
			id: "21",
			brand: "nokia",
			title: "Nokia 7.2",
			price: 299,
			img: "/img/nokia/Nokia_7_2.jpg",
			ram: "4GB",
			color: "Charcoal",
			year: 2019,
			reviews: []
		},
		{
			id: "22",
			brand: "nokia",
			title: "Nokia 5.4",
			price: 199,
			img: "/img/nokia/Nokia_5_4.jpg",
			ram: "4GB",
			color: "Polar Night",
			year: 2020,
			reviews: []
		},
		{
			id: "23",
			brand: "nokia",
			title: "Nokia 6.2",
			price: 249,
			img: "/img/nokia/Nokia_6_2.jpg",
			ram: "3GB",
			color: "Ceramic Black",
			year: 2019,
			reviews: []
		},
		{
			id: "24",
			brand: "nokia",
			title: "Nokia 8.3 5G",
			price: 499,
			img: "/img/nokia/Nokia_8_3_5G.jpg",
			ram: "8GB",
			color: "Polar Night",
			year: 2022,
			reviews: []
		},
		{
			id: "25",
			brand: "nokia",
			title: "Nokia 3.4",
			price: 149,
			img: "/img/nokia/Nokia_3_4.jpg",
			ram: "3GB",
			color: "Fjord",
			year: 2021,
			reviews: []
		},
		{
			id: "26",
			brand: "nokia",
			title: "Nokia 2.4",
			price: 119,
			img: "/img/nokia/Nokia_2_4.jpg",
			ram: "3GB",
			color: "Dusk",
			year: 2020,
			reviews: []
		},
		{
			id: "27",
			brand: "nokia",
			title: "Nokia 1 Plus",
			price: 99,
			img: "/img/nokia/Nokia_1_Plus.jpg",
			ram: "1GB",
			color: "Black",
			year: 2019,
			reviews: []
		},
		{
			id: "28",
			brand: "nokia",
			title: "Nokia 7 Plus",
			price: 349,
			img: "/img/nokia/Nokia_7_Plus.jpg",
			ram: "4GB",
			color: "Black/Copper",
			year: 2018,
			reviews: []
		},
		{
			id: "29",
			brand: "nokia",
			title: "Nokia 8 Sirocco",
			price: 499,
			img: "/img/nokia/Nokia_8_Sirocco.jpg",
			ram: "6GB",
			color: "Black",
			year: 2018,
			reviews: []
		},
	],
	redmi: [
		{
			id: "30",
			brand: "redmi",
			title: "a3",
			price: 20,
			img: "/img/redmi/redmia3.jpg",
			ram: "1 GB",
			color: "beige",
			year: 2005,
			reviews: []
		},
		{
			id: "31",
			brand: "redmi",
			title: "redmi6.",
			price: 31,
			img: "/img/redmi/Redmi6.jpg",
			ram: "2 GB",
			color: "grey",
			year: 2010,
			reviews: []
		},
		{
			id: "32",
			brand: "redmi",
			title: "note8",
			price: 70,
			img: "/img/redmi/redminote8.jpg",
			ram: "64 GB",
			color: "black",
			year: 2018,
			reviews: []
		},
		{
			id: "33",
			brand: "redmi",
			title: "a9",
			price: 65,
			img: "/img/redmi/redmi9a.jpg",
			ram: "64 GB",
			color: "aqua",
			year: 2005,
			reviews: []
		},
		{
			id: "34",
			brand: "redmi",
			title: "3SPrime ",
			price: 10,
			img: "/img/redmi/Redmi3SPrime.jpg",
			ram: "12 GB",
			color: "beige",
			year: 2004,
			reviews: []
		},
		{
			id: "35",
			brand: "redmi",
			title: "a2",
			price: 11,
			img: "/img/redmi/redmia2.webp",
			ram: "12 GB",
			color: "green",
			year: 2005,
			reviews: []
		},
		{
			id: "36",
			brand: "redmi",
			title: "redmi9",
			price: 21.5,
			img: "/img/redmi/Redmi9.webp",
			ram: "32 GB",
			color: "green",
			year: 2010,
			reviews: []
		},
		{
			id: "37",
			brand: "redmi",
			title: "Note12Pro",
			price: 68.5,
			img: "/img/redmi/RedmiNote12Pro.webp",
			ram: "126 GB",
			color: "black",
			year: 2023,
			reviews: []
		},
		{
			id: "38",
			brand: "redmi",
			title: "Note10",
			price: 27,
			img: "/img/redmi/RedmiNote10.jpg",
			ram: "32 GB",
			color: "black",
			year: 2015,
			reviews: []
		},
		{
			id: "39",
			brand: "redmi",
			title: "Redmi10",
			price: 30,
			img: "/img/redmi/Redmi10.webp",
			ram: "64 GB",
			color: "aqua",
			year: 2018,
			reviews: []
		},
	],
	samsung: [
		{
			id: "40",
			brand: "samsung",
			title: "Galaxy S23 Ultra",
			price: 1200,
			img: "/img/samsung/galaxyS23U.webp",
			ram: "12 GB",
			color: "Lavender",
			year: 2023,
			reviews: []
		},
		{
			id: "41",
			brand: "samsung",
			title: "Galaxy S22 Ultra",
			price: 785,
			img: "/img/samsung/galaxyS22U.webp",
			ram: "12 GB",
			color: "white",
			year: 2022,
			reviews: []
		},
		{
			id: "42",
			brand: "samsung",
			title: "Galaxy S21 Ultra",
			price: 380,
			img: "/img/samsung/galaxyS21U.webp",
			ram: "12 GB",
			color: "black",
			year: 2021,
			reviews: []
		},
		{
			id: "43",
			brand: "samsung",
			title: "Galaxy S20 Ultra",
			price: 320,
			img: "/img/samsung/galaxyS20U.webp",
			ram: "12 GB",
			color: "black",
			year: 2020,
			reviews: []
		},
		{
			id: "44",
			brand: "samsung",
			title: "Galaxy S10",
			price: 168,
			img: "/img/samsung/galaxyS10.webp",
			ram: "8 GB",
			color: "blue",
			year: 2019,
			reviews: []
		},
		{
			id: "45",
			brand: "samsung",
			title: "Galaxy S9",
			price: 720,
			img: "/img/samsung/galaxyS9.webp",
			ram: "4 GB",
			color: "blue",
			year: 2018,
			reviews: []
		},
		{
			id: "46",
			brand: "samsung",
			title: "Galaxy S8",
			price: 700,
			img: "/img/samsung/galaxyS8.webp",
			ram: "4 GB",
			color: "black",
			year: 2017,
			reviews: []
		},
		{
			id: "47",
			brand: "samsung",
			title: "Galaxy S7",
			price: 600,
			img: "/img/samsung/galaxyS7.webp",
			ram: "4 GB",
			color: "white",
			year: 2016,
			reviews: []
		},
		{
			id: "48",
			brand: "samsung",
			title: "Galaxy S6",
			price: 200,
			img: "/img/samsung/galaxyS6.webp",
			ram: "3 GB",
			color: "white",
			year: 2015,
			reviews: []
		},
		{
			id: "49",
			brand: "samsung",
			title: "Galaxy S5",
			price: 120,
			img: "/img/samsung/galaxyS5.webp",
			ram: "2 GB",
			color: "white",
			year: 2014,
			reviews: []
		},
	],
	xiaomi: [
		{
			id: "50",
			brand: "xiaomi",
			title: "Xiaomi",
			price: 56.5,
			img: "/img/xiaomi/xiaomi.jpg",
			ram: "12 GB",
			color: "black",
			year: 2010,
			reviews: []
		},
		{
			id: "51",
			brand: "xiaomi",
			title: "Xiaomi Poco C51.",
			price: 57.6,
			img: "/img/xiaomi/pocoC51.jpg",
			ram: "13 GB",
			color: "black",
			year: 2009,
			reviews: []
		},
		{
			id: "52",
			brand: "xiaomi",
			title: "Xiaomi Redmi 12.",
			price: 54.2,
			img: "/img/xiaomi/redmi12.jpg",
			ram: "16 GB",
			color: "blue",
			year: 2012,
			reviews: []
		},
		{
			id: "53",
			brand: "xiaomi",
			title: " Xiaomi Redmi Note 12 Pro 5G",
			price: 52.1,
			img: "/img/xiaomi/note12 5G.jpg",
			ram: "5 GB",
			color: "green",
			year: 2007,
			reviews: []
		},
		{
			id: "54",
			brand: "xiaomi",
			title: "Xiaomi black shark4  ",
			price: 50.9,
			img: "/img/xiaomi/blackShark.jpg",
			ram: "13 GB",
			color: "black",
			year: 2005,
			reviews: []
		},
		{
			id: "55",
			brand: "xiaomi",
			title: "Xiaomi Redmi Note 12S NFC.",
			price: 61.7,
			img: "/img/xiaomi/note12S.jpg",
			ram: "128 GB",
			color: "black",
			year: 2015,
			reviews: []
		},
		{
			id: "56",
			brand: "xiaomi",
			title: "Xiaomi Redmi Note 12 Pro Speed Edition",
			price: 41.5,
			img: "/img/xiaomi/pocoM6.jpg",
			ram: "4 GB",
			color: "green",
			year: 2020,
			reviews: []
		},
		{
			id: "57",
			brand: "xiaomi",
			title: "Xiaomi poco C50",
			price: 38.2,
			img: "/img/xiaomi/pocoC50.jpg",
			ram: "6 GB",
			color: "white",
			year: 2004,
			reviews: []
		},
		{
			id: "58",
			brand: "xiaomi",
			title: "Xiaomi poco M5s",
			price: 47.6,
			img: "/img/xiaomi/pocoM5s.jpg",
			ram: "12 GB",
			color: "gray",
			year: 2018,
			reviews: []
		},
		{
			id: "59",
			brand: "xiaomi",
			title: "Xiaomi Mix Fold 2",
			price: 65.0,
			img: "/img/xiaomi/mix-fold-2.jpg",
			ram: "9 GB",
			color: "black",
			year: 2017,
			reviews: []
		},
	],
};
